/* 
* Generated by
* 
*      _____ _          __  __      _     _
*     / ____| |        / _|/ _|    | |   | |
*    | (___ | | ____ _| |_| |_ ___ | | __| | ___ _ __
*     \___ \| |/ / _` |  _|  _/ _ \| |/ _` |/ _ \ '__|
*     ____) |   < (_| | | | || (_) | | (_| |  __/ |
*    |_____/|_|\_\__,_|_| |_| \___/|_|\__,_|\___|_|
*
* The code generator that works in many programming languages
*
*			https://www.skaffolder.com
*
*
* You can generate the code from the command-line
*       https://npmjs.com/package/skaffolder-cli
*
*       npm install -g skaffodler-cli
*
*   *   *   *   *   *   *   *   *   *   *   *   *   *   *   *
*
* To remove this comment please upgrade your plan here: 
*      https://app.skaffolder.com/#!/upgrade
*
* Or get up to 70% discount sharing your unique link:
*       https://beta.skaffolder.com/#!/register?friend=5d122668c0161c5b2b76f322
*
* You will get 10% discount for each one of your friends
* 
*/
// Import Libraries
import { Component, OnInit } from '@angular/core';
import { Location } from '@angular/common';
import { ActivatedRoute } from '@angular/router';
// Import Services
import { EventoService } from '../../services/evento.service';
import { Detalle_eventoService } from '../../services/detalle_evento.service';
import { ServicioService } from '../../services/servicio.service';
// Import Models
import { Evento } from '../../domain/newtest_db/evento';
import { Servicio } from '../../domain/newtest_db/servicio';
import { Detalle_evento } from '../../domain/newtest_db/detalle_evento';

// START - USED SERVICES
/**
* eventoService.create
*	@description CRUD ACTION create
*	@param evento obj Object to insert
*
* detalle_eventoService.findByid_evento
*	@description CRUD ACTION findByid_evento
*	@param Objectid key Id della risorsa id_evento da cercare
*
* eventoService.get
*	@description CRUD ACTION get
*	@param ObjectId id Id evento
*	@returns evento
*
* servicioService.list
*	@description CRUD ACTION list
*	@returns ARRAY OF servicio
*
* eventoService.update
*	@description CRUD ACTION update
*	@returns evento
*
*/
// END - USED SERVICES

/**
 * This component allows to edit a Evento
 */
@Component({
    selector: 'app-evento-edit',
    templateUrl: 'evento-edit.component.html',
    styleUrls: ['evento-edit.component.css']
})
export class EventoEditComponent implements OnInit {
    item: Evento;
    listEvento_servicio: Servicio[];
    listId_evento: Evento[];
    externalDetalle_evento: Detalle_evento[];
    model: Evento;
    formValid: Boolean;

    constructor(
    private eventoService: EventoService,
    private detalle_eventoService: Detalle_eventoService,
    private servicioService: ServicioService,
    private route: ActivatedRoute,
    private location: Location) {
        // Init item
        this.item = new Evento();
        this.externalDetalle_evento = [];
    }

    /**
     * Init
     */
    ngOnInit() {
        this.route.params.subscribe(param => {
            const id: string = param['id'];
            if (id !== 'new') {
                this.eventoService.get(id).subscribe(item => this.item = item);
                this.detalle_eventoService.findById_evento(id).subscribe(list => this.externalDetalle_evento = list);
            }
            // Get relations
            this.servicioService.list().subscribe(list => this.listEvento_servicio = list);
        });
    }


    /**
     * Save Evento
     *
     * @param {boolean} formValid Form validity check
     * @param Evento item Evento to save
     */
    save(formValid: boolean, item: Evento): void {
        this.formValid = formValid;
        if (formValid) {
            if (item._id) {
                this.eventoService.update(item).subscribe(data => this.goBack());
            } else {
                this.eventoService.create(item).subscribe(data => this.goBack());
            } 
        }
    }

    /**
     * Go Back
     */
    goBack(): void {
        this.location.back();
    }


}



