/* 
* Generated by
* 
*      _____ _          __  __      _     _
*     / ____| |        / _|/ _|    | |   | |
*    | (___ | | ____ _| |_| |_ ___ | | __| | ___ _ __
*     \___ \| |/ / _` |  _|  _/ _ \| |/ _` |/ _ \ '__|
*     ____) |   < (_| | | | || (_) | | (_| |  __/ |
*    |_____/|_|\_\__,_|_| |_| \___/|_|\__,_|\___|_|
*
* The code generator that works in many programming languages
*
*			https://www.skaffolder.com
*
*
* You can generate the code from the command-line
*       https://npmjs.com/package/skaffolder-cli
*
*       npm install -g skaffodler-cli
*
*   *   *   *   *   *   *   *   *   *   *   *   *   *   *   *
*
* To remove this comment please upgrade your plan here: 
*      https://app.skaffolder.com/#!/upgrade
*
* Or get up to 70% discount sharing your unique link:
*       https://beta.skaffolder.com/#!/register?friend=5d122668c0161c5b2b76f322
*
* You will get 10% discount for each one of your friends
* 
*/
/**
 *
 *
  _____                      _              _ _ _     _   _     _        __ _ _
 |  __ \                    | |            | (_) |   | | | |   (_)      / _(_) |
 | |  | | ___    _ __   ___ | |_    ___  __| |_| |_  | |_| |__  _ ___  | |_ _| | ___
 | |  | |/ _ \  | '_ \ / _ \| __|  / _ \/ _` | | __| | __| '_ \| / __| |  _| | |/ _ \
 | |__| | (_) | | | | | (_) | |_  |  __/ (_| | | |_  | |_| | | | \__ \ | | | | |  __/
 |_____/ \___/  |_| |_|\___/ \__|  \___|\__,_|_|\__|  \__|_| |_|_|___/ |_| |_|_|\___|

 * DO NOT EDIT THIS FILE!!
 *
 *  FOR CUSTOMIZE asistenciaBaseService PLEASE EDIT ../asistencia.service.ts
 *
 *  -- THIS FILE WILL BE OVERWRITTEN ON THE NEXT SKAFFOLDER'S CODE GENERATION --
 *
 */
 // DEPENDENCIES
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';
import { HttpClient } from '@angular/common/http';

// CONFIG
import { environment } from '../../../environments/environment';

// MODEL
import { Asistencia } from '../../domain/newtest_db/asistencia';

/**
 * THIS SERVICE MAKE HTTP REQUEST TO SERVER, FOR CUSTOMIZE IT EDIT ../asistencia.service.ts
 */

/*
 * SCHEMA DB asistencia
 *
	{
		avaya: {
			type: 'String'
		},
		confirmacion: {
			type: 'Boolean'
		},
		tiempo: {
			type: 'Number'
		},
		//RELATIONS
		//EXTERNAL RELATIONS
		id_detalle_asistencia: {
			type: Schema.ObjectId,
			ref : "asistencia"
		},
		id_usuario_asistencia: {
			type: Schema.ObjectId,
			ref : "asistencia"
		},
	}
 *
 */
@Injectable()
export class AsistenciaBaseService {

    contextUrl: string = environment.endpoint + '/asistencia';
    constructor(
        protected http: HttpClient
        ) { }

    // CRUD METHODS

    /**
    * asistenciaService.delete
    *   @description CRUD ACTION delete
    *   @param ObjectId id Id asistencia
    *
    */
    remove(id: string): Observable<void> {
        return this.http
            .delete<void>(this.contextUrl + '/' + id)
            .pipe(map(data => data));
    }


    // Custom APIs


    /**
    * asistenciaService.add
    *   @description Agrega una nueva asistencia a un usuario
    *
    */
    add(...params: any[]): Observable<any> {
        return this.http
            .post<any>(this.contextUrl + '/add', {})
            .pipe(
                map(response => response)
            );
    }

}
